/**
 * Label Design Templates and Layout Configurations
 */

const BuiltinTemplates = [
  {
    id: 'standard-retail',
    name: 'Standard Retail (Store + Barcode + Price)',
    presetId: '50x25',
    format: 'CODE128',
    showStoreName: true,
    storeName: 'MY STORE',
    showTitle: true,
    showPrice: true,
    showMrp: false,
    currencySymbol: '$',
    showSku: true,
    showExtraInfo: false,
    extraInfo: '',
    barcodeHeight: 38,
    barcodeModuleWidth: 2,
    includeBarcodeText: true,
    align: 'center',
    borderStyle: 'none', // none, solid, dashed
    fontFamily: 'Inter',
    headerFontSize: 9,
    titleFontSize: 11,
    priceFontSize: 14,
    skuFontSize: 8.5,
    isBuiltin: true
  },
  {
    id: 'clearance-discount',
    name: 'Clearance & Sale Tag (MRP vs Price)',
    presetId: '50x30',
    format: 'CODE128',
    showStoreName: true,
    storeName: 'SPECIAL OFFER',
    showTitle: true,
    showPrice: true,
    showMrp: true,
    currencySymbol: '$',
    showSku: true,
    showExtraInfo: true,
    extraInfo: 'SAVE 30%',
    barcodeHeight: 40,
    barcodeModuleWidth: 2,
    includeBarcodeText: true,
    align: 'center',
    borderStyle: 'dashed',
    fontFamily: 'Inter',
    headerFontSize: 9,
    titleFontSize: 11,
    priceFontSize: 15,
    skuFontSize: 8.5,
    isBuiltin: true
  },
  {
    id: 'compact-jewelry',
    name: 'Compact Item & Jewelry Tag',
    presetId: '40x20',
    format: 'CODE128',
    showStoreName: false,
    storeName: '',
    showTitle: true,
    showPrice: true,
    showMrp: false,
    currencySymbol: '$',
    showSku: true,
    showExtraInfo: false,
    extraInfo: '',
    barcodeHeight: 28,
    barcodeModuleWidth: 1.8,
    includeBarcodeText: false,
    align: 'center',
    borderStyle: 'none',
    fontFamily: 'Inter',
    headerFontSize: 8,
    titleFontSize: 9,
    priceFontSize: 11.5,
    skuFontSize: 7.5,
    isBuiltin: true
  },
  {
    id: 'supermarket-ean13',
    name: 'EAN-13 Supermarket Tag',
    presetId: '50x30',
    format: 'EAN13',
    showStoreName: true,
    storeName: 'FRESH MART',
    showTitle: true,
    showPrice: true,
    showMrp: false,
    currencySymbol: '$',
    showSku: false,
    showExtraInfo: true,
    extraInfo: 'Net Wt: 500g',
    barcodeHeight: 45,
    barcodeModuleWidth: 2,
    includeBarcodeText: true,
    align: 'center',
    borderStyle: 'none',
    fontFamily: 'Inter',
    headerFontSize: 9,
    titleFontSize: 11,
    priceFontSize: 15,
    skuFontSize: 8.5,
    isBuiltin: true
  },
  {
    id: 'warehouse-bin',
    name: 'Warehouse & Inventory Bin Tag',
    presetId: '60x40',
    format: 'CODE128',
    showStoreName: true,
    storeName: 'WAREHOUSE AISLE-B',
    showTitle: true,
    showPrice: false,
    showMrp: false,
    currencySymbol: '$',
    showSku: true,
    showExtraInfo: true,
    extraInfo: 'Loc: B-12-04 | Pack: 24',
    barcodeHeight: 56,
    barcodeModuleWidth: 2.2,
    includeBarcodeText: true,
    align: 'center',
    borderStyle: 'solid',
    fontFamily: 'Inter',
    headerFontSize: 10,
    titleFontSize: 13,
    priceFontSize: 14,
    skuFontSize: 10,
    isBuiltin: true
  },
  {
    id: 'barcode-only',
    name: 'Pure Barcode Only (Direct Scan)',
    presetId: '50x25',
    format: 'CODE128',
    showStoreName: false,
    storeName: '',
    showTitle: false,
    showPrice: false,
    showMrp: false,
    currencySymbol: '$',
    showSku: false,
    showExtraInfo: false,
    extraInfo: '',
    barcodeHeight: 52,
    barcodeModuleWidth: 2.4,
    includeBarcodeText: true,
    align: 'center',
    borderStyle: 'none',
    fontFamily: 'Inter',
    headerFontSize: 9,
    titleFontSize: 10,
    priceFontSize: 12,
    skuFontSize: 8.5,
    isBuiltin: true
  }
];

if (typeof window !== 'undefined') {
  window.BuiltinTemplates = BuiltinTemplates;
}
